name: CI

on: [push]

jobs:
  build:
    runs-on: maven:3.8.4-openjdk-17
    steps:
    - name: Gerando build
      run: mvn package -Dmaven.test.skip
  test:
    runs-on: maven:3.8.4-openjdk-17
    steps:
    - name: Rodando teste unidade
      run: mvn test